### ISSUE TITLE
Update to implement async background load

### ISSUE THREAD

**Issue by matthewacme** [madskristensen/Farticus#3]
Any chance you could update this to implement async background load.

Strangely enough I miss my fart on unsuccessful build. it at least made me smile at my failure.

**Comment by madskristensen** [comment]
This should now be fixed. Check out the CI build and let me know it if works for you: http://vsixgallery.com/extension/1324ce08-8b25-440c-8d5c-07e1fa0cce4a/

**Comment by matthewacme** [comment]
You rock, as always…

Thanks, I’m smiling again, at my own failures.

so yep, it now works without the startup warning!


[Acme Logo]
Matthew C. Hintzen | Windows Washer
•
w – matthew@acmeaom.com
p – 321.234.8839
•
Flightwise.com MyRadar.com
